#pragma once

#if PLATFORM == GLFW

/* The unknown key */
#define ENGINE_KEY_UNKNOWN -1

/* Printable keys */
#define ENGINE_KEY_SPACE 32
#define ENGINE_KEY_APOSTROPHE 39 /* ' */
#define ENGINE_KEY_COMMA 44      /* , */
#define ENGINE_KEY_MINUS 45      /* - */
#define ENGINE_KEY_PERIOD 46     /* . */
#define ENGINE_KEY_SLASH 47      /* / */
#define ENGINE_KEY_0 48
#define ENGINE_KEY_1 49
#define ENGINE_KEY_2 50
#define ENGINE_KEY_3 51
#define ENGINE_KEY_4 52
#define ENGINE_KEY_5 53
#define ENGINE_KEY_6 54
#define ENGINE_KEY_7 55
#define ENGINE_KEY_8 56
#define ENGINE_KEY_9 57
#define ENGINE_KEY_SEMICOLON 59 /* ; */
#define ENGINE_KEY_EQUAL 61     /* = */
#define ENGINE_KEY_A 65
#define ENGINE_KEY_B 66
#define ENGINE_KEY_C 67
#define ENGINE_KEY_D 68
#define ENGINE_KEY_E 69
#define ENGINE_KEY_F 70
#define ENGINE_KEY_G 71
#define ENGINE_KEY_H 72
#define ENGINE_KEY_I 73
#define ENGINE_KEY_J 74
#define ENGINE_KEY_K 75
#define ENGINE_KEY_L 76
#define ENGINE_KEY_M 77
#define ENGINE_KEY_N 78
#define ENGINE_KEY_O 79
#define ENGINE_KEY_P 80
#define ENGINE_KEY_Q 81
#define ENGINE_KEY_R 82
#define ENGINE_KEY_S 83
#define ENGINE_KEY_T 84
#define ENGINE_KEY_U 85
#define ENGINE_KEY_V 86
#define ENGINE_KEY_W 87
#define ENGINE_KEY_X 88
#define ENGINE_KEY_Y 89
#define ENGINE_KEY_Z 90
#define ENGINE_KEY_LEFT_BRACKET 91  /* [ */
#define ENGINE_KEY_BACKSLASH 92     /* \ */
#define ENGINE_KEY_RIGHT_BRACKET 93 /* ] */
#define ENGINE_KEY_GRAVE_ACCENT 96  /* ` */
#define ENGINE_KEY_WORLD_1 161      /* non-US #1 */
#define ENGINE_KEY_WORLD_2 162      /* non-US #2 */

/* Function keys */
#define ENGINE_KEY_ESCAPE 256
#define ENGINE_KEY_ENTER 257
#define ENGINE_KEY_TAB 258
#define ENGINE_KEY_BACKSPACE 259
#define ENGINE_KEY_INSERT 260
#define ENGINE_KEY_DELETE 261
#define ENGINE_KEY_RIGHT 262
#define ENGINE_KEY_LEFT 263
#define ENGINE_KEY_DOWN 264
#define ENGINE_KEY_UP 265
#define ENGINE_KEY_PAGE_UP 266
#define ENGINE_KEY_PAGE_DOWN 267
#define ENGINE_KEY_HOME 268
#define ENGINE_KEY_END 269
#define ENGINE_KEY_CAPS_LOCK 280
#define ENGINE_KEY_SCROLL_LOCK 281
#define ENGINE_KEY_NUM_LOCK 282
#define ENGINE_KEY_PRINT_SCREEN 283
#define ENGINE_KEY_PAUSE 284
#define ENGINE_KEY_F1 290
#define ENGINE_KEY_F2 291
#define ENGINE_KEY_F3 292
#define ENGINE_KEY_F4 293
#define ENGINE_KEY_F5 294
#define ENGINE_KEY_F6 295
#define ENGINE_KEY_F7 296
#define ENGINE_KEY_F8 297
#define ENGINE_KEY_F9 298
#define ENGINE_KEY_F10 299
#define ENGINE_KEY_F11 300
#define ENGINE_KEY_F12 301
#define ENGINE_KEY_F13 302
#define ENGINE_KEY_F14 303
#define ENGINE_KEY_F15 304
#define ENGINE_KEY_F16 305
#define ENGINE_KEY_F17 306
#define ENGINE_KEY_F18 307
#define ENGINE_KEY_F19 308
#define ENGINE_KEY_F20 309
#define ENGINE_KEY_F21 310
#define ENGINE_KEY_F22 311
#define ENGINE_KEY_F23 312
#define ENGINE_KEY_F24 313
#define ENGINE_KEY_F25 314
#define ENGINE_KEY_KP_0 320
#define ENGINE_KEY_KP_1 321
#define ENGINE_KEY_KP_2 322
#define ENGINE_KEY_KP_3 323
#define ENGINE_KEY_KP_4 324
#define ENGINE_KEY_KP_5 325
#define ENGINE_KEY_KP_6 326
#define ENGINE_KEY_KP_7 327
#define ENGINE_KEY_KP_8 328
#define ENGINE_KEY_KP_9 329
#define ENGINE_KEY_KP_DECIMAL 330
#define ENGINE_KEY_KP_DIVIDE 331
#define ENGINE_KEY_KP_MULTIPLY 332
#define ENGINE_KEY_KP_SUBTRACT 333
#define ENGINE_KEY_KP_ADD 334
#define ENGINE_KEY_KP_ENTER 335
#define ENGINE_KEY_KP_EQUAL 336
#define ENGINE_KEY_LEFT_SHIFT 340
#define ENGINE_KEY_LEFT_CONTROL 341
#define ENGINE_KEY_LEFT_ALT 342
#define ENGINE_KEY_LEFT_SUPER 343
#define ENGINE_KEY_RIGHT_SHIFT 344
#define ENGINE_KEY_RIGHT_CONTROL 345
#define ENGINE_KEY_RIGHT_ALT 346
#define ENGINE_KEY_RIGHT_SUPER 347
#define ENGINE_KEY_MENU 348

#define ENGINE_KEY_LAST ENGINE_KEY_MENU

#else

/* The unknown key */
#define ENGINE_KEY_UNKNOWN 0

/* Printable keys */
#define ENGINE_KEY_SPACE 0
#define ENGINE_KEY_APOSTROPHE 0 /* ' */
#define ENGINE_KEY_COMMA 0      /* , */
#define ENGINE_KEY_MINUS 0      /* - */
#define ENGINE_KEY_PERIOD 0     /* . */
#define ENGINE_KEY_SLASH 0      /* / */
#define ENGINE_KEY_0 0
#define ENGINE_KEY_1 0
#define ENGINE_KEY_2 0
#define ENGINE_KEY_3 0
#define ENGINE_KEY_4 0
#define ENGINE_KEY_5 0
#define ENGINE_KEY_6 0
#define ENGINE_KEY_7 0
#define ENGINE_KEY_8 0
#define ENGINE_KEY_9 0
#define ENGINE_KEY_SEMICOLON 0 /* ; */
#define ENGINE_KEY_EQUAL 0     /* = */
#define ENGINE_KEY_A 0
#define ENGINE_KEY_B 0
#define ENGINE_KEY_C 0
#define ENGINE_KEY_D 0
#define ENGINE_KEY_E 0
#define ENGINE_KEY_F 0
#define ENGINE_KEY_G 0
#define ENGINE_KEY_H 0
#define ENGINE_KEY_I 0
#define ENGINE_KEY_J 0
#define ENGINE_KEY_K 0
#define ENGINE_KEY_L 0
#define ENGINE_KEY_M 0
#define ENGINE_KEY_N 0
#define ENGINE_KEY_O 0
#define ENGINE_KEY_P 0
#define ENGINE_KEY_Q 0
#define ENGINE_KEY_R 0
#define ENGINE_KEY_S 0
#define ENGINE_KEY_T 0
#define ENGINE_KEY_U 0
#define ENGINE_KEY_V 0
#define ENGINE_KEY_W 0
#define ENGINE_KEY_X 0
#define ENGINE_KEY_Y 0
#define ENGINE_KEY_Z 0
#define ENGINE_KEY_LEFT_BRACKET 0  /* [ */
#define ENGINE_KEY_BACKSLASH 0     /* \ */
#define ENGINE_KEY_RIGHT_BRACKET 0 /* ] */
#define ENGINE_KEY_GRAVE_ACCENT 0  /* ` */
#define ENGINE_KEY_WORLD_1 0       /* non-US #1 */
#define ENGINE_KEY_WORLD_2 0       /* non-US #2 */

/* Function keys */
#define ENGINE_KEY_ESCAPE 0
#define ENGINE_KEY_ENTER 0
#define ENGINE_KEY_TAB 0
#define ENGINE_KEY_BACKSPACE 0
#define ENGINE_KEY_INSERT 0
#define ENGINE_KEY_DELETE 0
#define ENGINE_KEY_RIGHT 0
#define ENGINE_KEY_LEFT 0
#define ENGINE_KEY_DOWN 0
#define ENGINE_KEY_UP 0
#define ENGINE_KEY_PAGE_UP 0
#define ENGINE_KEY_PAGE_DOWN 0
#define ENGINE_KEY_HOME 0
#define ENGINE_KEY_END 0
#define ENGINE_KEY_CAPS_LOCK 0
#define ENGINE_KEY_SCROLL_LOCK 0
#define ENGINE_KEY_NUM_LOCK 0
#define ENGINE_KEY_PRINT_SCREEN 0
#define ENGINE_KEY_PAUSE 0
#define ENGINE_KEY_F1 0
#define ENGINE_KEY_F2 0
#define ENGINE_KEY_F3 0
#define ENGINE_KEY_F4 0
#define ENGINE_KEY_F5 0
#define ENGINE_KEY_F6 0
#define ENGINE_KEY_F7 0
#define ENGINE_KEY_F8 0
#define ENGINE_KEY_F9 0
#define ENGINE_KEY_F10 0
#define ENGINE_KEY_F11 0
#define ENGINE_KEY_F12 0
#define ENGINE_KEY_F13 0
#define ENGINE_KEY_F14 0
#define ENGINE_KEY_F15 0
#define ENGINE_KEY_F16 0
#define ENGINE_KEY_F17 0
#define ENGINE_KEY_F18 0
#define ENGINE_KEY_F19 0
#define ENGINE_KEY_F20 0
#define ENGINE_KEY_F21 0
#define ENGINE_KEY_F22 0
#define ENGINE_KEY_F23 0
#define ENGINE_KEY_F24 0
#define ENGINE_KEY_F25 0
#define ENGINE_KEY_KP_0 0
#define ENGINE_KEY_KP_1 0
#define ENGINE_KEY_KP_2 0
#define ENGINE_KEY_KP_3 0
#define ENGINE_KEY_KP_4 0
#define ENGINE_KEY_KP_5 0
#define ENGINE_KEY_KP_6 0
#define ENGINE_KEY_KP_7 0
#define ENGINE_KEY_KP_8 0
#define ENGINE_KEY_KP_9 0
#define ENGINE_KEY_KP_DECIMAL 0
#define ENGINE_KEY_KP_DIVIDE 0
#define ENGINE_KEY_KP_MULTIPLY 0
#define ENGINE_KEY_KP_SUBTRACT 0
#define ENGINE_KEY_KP_ADD 0
#define ENGINE_KEY_KP_ENTER 0
#define ENGINE_KEY_KP_EQUAL 0
#define ENGINE_KEY_LEFT_SHIFT 0
#define ENGINE_KEY_LEFT_CONTROL 0
#define ENGINE_KEY_LEFT_ALT 0
#define ENGINE_KEY_LEFT_SUPER 0
#define ENGINE_KEY_RIGHT_SHIFT 0
#define ENGINE_KEY_RIGHT_CONTROL 0
#define ENGINE_KEY_RIGHT_ALT 0
#define ENGINE_KEY_RIGHT_SUPER 0
#define ENGINE_KEY_MENU 0

#define ENGINE_KEY_LAST ENGINE_KEY_MENU

#endif